name: "vertigo_case"
version: '1.0.0'

profile: "fiery-tribute-466414-s2"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  daily_metrics:
    +materialized: table
    +partition_by:
      field: event_date
      data_type: date
    +cluster_by: ["country", "platform"]