version: 2

sources:
  - name: bi_projects
    description: Raw gaming data
    tables:
      - name: dataset
        description: User-level daily metrics
        columns:
          - name: user_id
            tests:
              - not_null
          - name: event_date
            tests:
              - not_null
          - name: country
            tests:
              - not_null
          - name: platform
            tests:
              - not_null

models:
  - name: daily_metrics
    description: Daily aggregated gaming metrics
    columns:
      - name: event_date
        tests:
          - not_null
      - name: country
        tests:
          - not_null
      - name: platform
        tests:
          - not_null
      - name: dau
        tests:
          - not_null